"""Wire parsing and validation for the Pocketful API.

**Reject, never coerce.** Every function here either returns a value that is
exactly the type plan §2.2 names, or raises :class:`~api.errors.ApiError`. No
amount is ever produced by parsing a string or a floating-point value: money is
an integer count of minor units, or it is refused.
"""

from __future__ import annotations

import hashlib
import json

from ledger import MAX_MINOR

from .errors import (
    ApiError,
    INVALID_AMOUNT,
    INVALID_CURSOR,
    INVALID_IDEMPOTENCY_KEY,
    INVALID_LIMIT,
    INVALID_REQUEST,
    MALFORMED_JSON,
)

# §2.2: the key is a client-generated UUIDv4; the cap keeps a hostile client
# from parking unbounded text in the idempotency table's primary key.
MAX_IDEMPOTENCY_KEY_LEN = 255

DEFAULT_ACTIVITY_LIMIT = 50
MAX_ACTIVITY_LIMIT = 500


# -- bodies -------------------------------------------------------------------


def parse_json_body(raw: bytes | None) -> object:
    """Decode the request body as JSON. Malformed input is a 400, never a guess."""
    if raw is None:
        raise ApiError(400, MALFORMED_JSON, "request body is required")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ApiError(400, MALFORMED_JSON, "request body is not valid UTF-8") from exc
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise ApiError(400, MALFORMED_JSON, f"request body is not valid JSON: {exc.msg}") from exc


def require_object(payload: object, *, what: str) -> dict:
    if not isinstance(payload, dict):
        raise ApiError(400, INVALID_REQUEST, f"{what} must be a JSON object")
    return payload


def require_non_empty_str(raw: dict, field: str) -> str:
    if field not in raw:
        raise ApiError(400, INVALID_REQUEST, f"{field} is required")
    value = raw[field]
    if not isinstance(value, str) or value == "":
        raise ApiError(400, INVALID_REQUEST, f"{field} must be a non-empty string")
    return value


def require_currency(raw: dict, field: str = "currency") -> str:
    value = require_non_empty_str(raw, field)
    if len(value) != 3 or not value.isascii() or not value.isalpha() or not value.isupper():
        raise ApiError(400, INVALID_REQUEST,
                       f"{field} must be a 3-letter ISO-4217 code, got {value!r}")
    return value


def require_bool(raw: dict, field: str, default: bool) -> bool:
    """A JSON boolean, or the default. ``1`` is not ``true`` here either."""
    if field not in raw:
        return default
    value = raw[field]
    if type(value) is not bool:
        raise ApiError(400, INVALID_REQUEST, f"{field} must be a JSON boolean")
    return value


def optional_account_id(raw: dict) -> str | None:
    """An optional client-chosen account id.

    §2.2's 201 body carries ``account_id`` but its request body does not, so the
    id is normally server-generated. Accepting an explicit one is what makes the
    409 ``account_exists`` path reachable at all; absent, a UUIDv4 hex is
    generated by the caller.
    """
    if "account_id" not in raw or raw["account_id"] is None:
        return None
    value = raw["account_id"]
    if not isinstance(value, str) or value == "":
        raise ApiError(400, INVALID_REQUEST, "account_id must be a non-empty string")
    return value


def require_amount_minor(raw: dict, field: str = "amount_minor") -> int:
    """§2.2: ``type(v) is int`` — explicitly **not** ``bool`` — and ``0 < v <= MAX_MINOR``.

    Rejected here, never converted: ``12.34`` (a float), ``"12.34"`` and
    ``"500"`` (strings), ``true`` (a ``bool``, which is an ``int`` subclass in
    Python), ``0``, and ``-500``.
    """
    if field not in raw:
        raise ApiError(422, INVALID_AMOUNT, f"{field} is required")
    value = raw[field]
    if type(value) is not int:
        raise ApiError(422, INVALID_AMOUNT,
                       f"{field} must be a JSON integer of minor units, "
                       f"got {type(value).__name__}")
    if value <= 0:
        raise ApiError(422, INVALID_AMOUNT, f"{field} must be positive, got {value}")
    if value > MAX_MINOR:
        raise ApiError(422, INVALID_AMOUNT, f"{field} exceeds MAX_MINOR ({MAX_MINOR})")
    return value


def require_idempotency_key(headers: object) -> str:
    """The key is a client-supplied header: present, non-blank, at most 255 chars."""
    key = headers.get("Idempotency-Key")
    if key is None or key.strip() == "":
        raise ApiError(400, INVALID_IDEMPOTENCY_KEY, "Idempotency-Key header is required")
    if len(key) > MAX_IDEMPOTENCY_KEY_LEN:
        raise ApiError(400, INVALID_IDEMPOTENCY_KEY,
                       f"Idempotency-Key must be at most {MAX_IDEMPOTENCY_KEY_LEN} chars, "
                       f"got {len(key)}")
    return key


def request_fingerprint(*, from_account_id: str, to_account_id: str,
                        amount_minor: int, currency: str) -> str:
    """A canonical hash of the transfer body.

    It exists **only** so a repeated key carrying a different body can be
    detected (INVARIANTS §3). It is explicitly not the key — deriving the key
    from the body is forbidden, and the client's key is stored verbatim
    alongside this value. Integer minor units only; nothing here is rounded.
    """
    canonical = json.dumps(
        [from_account_id, to_account_id, amount_minor, currency],
        separators=(",", ":"),
        ensure_ascii=True,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# -- query strings ------------------------------------------------------------


def parse_limit(raw_value: str | None) -> int:
    """Activity page size. Absent means the §2.2 default of 50."""
    if raw_value is None or raw_value == "":
        return DEFAULT_ACTIVITY_LIMIT
    try:
        value = int(raw_value, 10)
    except (TypeError, ValueError) as exc:
        raise ApiError(400, INVALID_LIMIT,
                       f"limit must be an integer, got {raw_value!r}") from exc
    if value < 1 or value > MAX_ACTIVITY_LIMIT:
        raise ApiError(400, INVALID_LIMIT,
                       f"limit must be between 1 and {MAX_ACTIVITY_LIMIT}, got {value}")
    return value


def parse_before(raw_value: str | None) -> str | None:
    """Keyset cursor: strictly older than this entry id."""
    if raw_value is None or raw_value == "":
        return None
    try:
        value = int(raw_value, 10)
    except (TypeError, ValueError) as exc:
        raise ApiError(400, INVALID_CURSOR,
                       f"before must be an entry id, got {raw_value!r}") from exc
    if value < 1:
        raise ApiError(400, INVALID_CURSOR,
                       f"before must be a positive entry id, got {value}")
    return str(value)
